version: 1.0                                      # stack-schema version 1.0

name: reactjs-flask-mysqldb-redis-algolia         # stack-template name by stack-template author
description: reactjs flask mysqldb redis algolia  # stack-template description by stack-template author

tags:                                             # stack-template tags
- stack-template-flask-mysql
- stack-by-phoenix24
- composed stack
- python 3.9
- flask 2.0.2
- mysql 5.1
- aloglia
- redis
- apache 2 licensed

configs:

  repository:                                     # stack-template artifact generated to stack-instance 
    name: ${stack.input.repo-name}                
    branch-protection:
      parameters:
        branch: main
        enforce_admins: true
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
        allow_deletions: false
        allow_force_pushes: false 
    description: "new repository created from ${stack.template.name}"
    tags:                                         # stack-template tags to be added to generated stack-instance repository
    - stack-starter
    - [${stack.input.tags}]

  wikis:                                          # stack-template settings to be added to generated stack-instance repository
    enabled: true

  issues:                                         # stack-template settings to be added to generated stack-instance repository
    enabled: true

  environments:                                   # stack-template environments to be added to generated stack-instance
    - name: review                                # stack-template environment added to generated stack-instance
      parameters:
        name: review
        wait_timer: 30
        protected_branches: false
        custom_branch_policies: true
        secret_var1: val1
        secret_var2: val2
      description: "review env for ${stack.input.repo-name}"

    - name: production                            # stack-template environment added to generated stack-instance
      parameters:
        name: production
        wait_timer: 60
        secret_var1: val1
      description: "production env for ${stack.input.repo-name}"

  github-apps:                                    # stack-template apps added to generated stack-instance repository
    - name: Azure
    - name: codetree

  vulnerability-alerts:                           # stack-template settings applied to generated stack-instance repository
    enabled: true

  automated-security-fixes:                       # stack-template settings applied to generated stack-instance repository
    enabled: true




initialize:

  - workflow:
    path: "repo-init.yaml"                        # stack-template workflow path is __relative__ to .github/stacks
    inputs:
      key1: ${stack.input.wflow-key3}             # stack input parameter key name must be unique, 
      key2: ${stack.input.wflow-key4}             #      because ${stack.input} is a common namespace
    runner-image: ubuntu-latest                   
                                                  # stack-template inputs (or values) 
                                                  # ⚠️  - not overrided

                                                  # stack-template exports to stack-instance
                                                  # ⚠️  - STACK_GITHUB_REPO_URL
                                                  # ⚠️  - STACK_GITHUB_REPO_WIKI
                                                  # ⚠️  - STACK_GITHUB_REPO_ISSUES
                                                  #
                                                  # ⚠️  - STACK_GITHUB_APPS_CODETREE
                                                  # ⚠️  - STACK_GITHUB_APPS_AZURE
                                                  #
                                                  # ⚠️  - STACK_GITHUB_ENVRONMENT_REVIEW
                                                  # ⚠️  - STACK_GITHUB_ENVRONMENT_PRODUCTION

                                                  # stack-template artifacts to stack-instance
                                                  # ⚠️  - a github repository
                                                  # ⚠️  - a github repository-wiki
                                                  # ⚠️  - a github repository-issues
                                                  # 
                                                  # ⚠️  - a github repository-app-codetree
                                                  # ⚠️  - a github repository-app-azure
                                                  # 
                                                  # ⚠️  - a github repository-env-review
                                                  # ⚠️  - a github repository-env-production

  - workflow:
    path: "initialize-gcp-cloudrun.yaml"          # stack-template workflow path is __relative__ to .github/stacks
    inputs:
      key1: ${stack.input.wflow-key3}             # stack-template input parameter key name must be unique,
      key2: ${stack.input.wflow-key4}             #      because ${stack.input} is a common namespace
    runner-image: ubuntu-latest

                                                  # once executed, may exports values to generated stack-instance
                                                  # ⚠️  exported values are key-value pairs
                                                  # ⚠️  exported values are generated artifacts (post execution)

                                                  # ⚠️  exports from stack-template
                                                  # ⚠️    export CLOUDRUN_APP_URL
                                                  # ⚠️    export CLOUDRUN_DOCKER_IMAGE
                                                  
                                                  # ⚠️  artifacts from stack-template added to stack-instance 
                                                  # ⚠️    worfkow/build.yaml
                                                  # ⚠️    worfkow/deploy.yaml
                                                  # ⚠️    cloudrun app service




  - workflow:
    path: "repo-init.yaml"                        # stack-template workflow path is __relative__ to .github/stacks
    inputs:
      key1: ${stack.input.wflow-key3}             # stack input parameter key name must be unique, 
      key2: ${stack.input.wflow-key4}             #      because ${stack.input} is a common namespace
    runner-image: ubuntu-latest                   
                                                  # stack-template inputs (or values) 
                                                  # ⚠️  - not overrided

                                                  # stack-template exports to stack-instance
                                                  # ⚠️  - STACK_GITHUB_REPO_URL
                                                  # ⚠️  - STACK_GITHUB_REPO_WIKI
                                                  # ⚠️  - STACK_GITHUB_REPO_ISSUES
                                                  #
                                                  # ⚠️  - STACK_GITHUB_APPS_CODETREE
                                                  # ⚠️  - STACK_GITHUB_APPS_AZURE
                                                  #
                                                  # ⚠️  - STACK_GITHUB_ENVRONMENT_REVIEW
                                                  # ⚠️  - STACK_GITHUB_ENVRONMENT_PRODUCTION

                                                  # stack-template artifacts to stack-instance
                                                  # ⚠️  - a github repository
                                                  # ⚠️  - a github repository-wiki
                                                  # ⚠️  - a github repository-issues
                                                  # 
                                                  # ⚠️  - a github repository-app-codetree
                                                  # ⚠️  - a github repository-app-azure
                                                  # 
                                                  # ⚠️  - a github repository-env-review
                                                  # ⚠️  - a github repository-env-production

  - workflow:
    path: "initialize-gcp-cloudrun.yaml"          # stack-template workflow path is __relative__ to .github/stacks
    inputs:
      key1: ${stack.input.wflow-key3}             # stack-template input parameter key name must be unique,
      key2: ${stack.input.wflow-key4}             #      because ${stack.input} is a common namespace
    runner-image: ubuntu-latest

                                                  # once executed, may exports values to generated stack-instance
                                                  # ⚠️  exported values are key-value pairs
                                                  # ⚠️  exported values are generated artifacts (post execution)

                                                  # ⚠️  exports from stack-template
                                                  # ⚠️    export CLOUDRUN_APP_URL
                                                  # ⚠️    export CLOUDRUN_DOCKER_IMAGE
                                                  
                                                  # ⚠️  artifacts from stack-template added to stack-instance 
                                                  # ⚠️    worfkow/build.yaml
                                                  # ⚠️    worfkow/deploy.yaml
                                                  # ⚠️    cloudrun app service



  - workflow:                                     # initialize provision-gcp-mysql
    path: "provision-gcp-mysql.yaml"              # 
    inputs:                                       # 
      key1: ${stack.input.wflow-key1}             # stack-template inputs (or values) 
      key2: ${stack.input.wflow-key2}             # ⚠️  - not overrided
    runner-image: ubuntu-latest                   #
                                                  # stack-template exports to stack-instance
                                                  # ⚠️  - STACK_MYSQLDB_URL
                                                  # 
                                                  # stack-template artifacts to stack-instance
                                                  # ⚠️  - a gcp mysqldb instance



  - workflow:                                     # initialize provision-gcp-redis
    path: "provision-gcp-redis.yaml"              # 
    inputs:                                       # 
      key1: ${stack.input.wflow-key1}             # stack-template inputs (or values) 
      key2: ${stack.input.wflow-key2}             # ⚠️  - not overrided
    runner-image: ubuntu-latest                   #
                                                  # stack-template exports to stack-instance
                                                  # ⚠️  - STACK_REDIS_URL
                                                  # 
                                                  # stack-template artifacts to stack-instance
                                                  # ⚠️  - a gcp redis instance



  - workflow:                                     # initialize provision-gcp-redis
    path: "provision-gcp-redis.yaml"              # 
    inputs:                                       # 
      key1: ${stack.input.wflow-key1}             # stack-template inputs (or values) 
      key2: ${stack.input.wflow-key2}             # ⚠️  - not overrided
    runner-image: ubuntu-latest                   #
                                                  # stack-template exports to stack-instance
                                                  # ⚠️  exports STACK_ALGOLIA_URL
                                                  #
                                                  # stack-template artifacts to stack-instance
                                                  # ⚠️  - an algolia instance
