version: 1.0                                      # stack-schema version 1.0

name: reactjs-flask-mysqldb-redis-algolia         # stack-template name by stack-template author
description: reactjs flask mysqldb redis algolia  # stack-template description by stack-template author

tags:                                             # stack-template tags
- stack-template-flask-mysql
- stack-by-phoenix24
- composed stack
- python 3.9
- flask 2.0.2
- mysql 5.1
- aloglia
- redis
- apache 2 licensed

composes:                                         # stack-composition via stack layering
  - stack: thetestbed/stack-template-reactjs-app  # stack added 
    version: 1                                    # stack parameters via values.yaml

  - stack: thetestbed/stack-template-flask-app    # stack added 
    version: 1                                    # stack parameters via values.yaml

  - stack: thetestbed/stack-template-gcp-redis    # stack added 
    version: 3.1                                  # stack parameters via values.yaml
    
  - stack: thetestbed/stack-template-gcp-mysqldb  # stack added 
    version: 3.1                                  # stack parameters via values.yaml
        
  - stack: thetestbed/stack-template-algolia      # stack added 
    version: 3.1                                  # stack parameters via values.yaml

                                                  # stack-template.yaml once executed, exports following to generated stack
                                                  # ⚠️
                                                  # ⚠️  exports from 1st stack, STACK_GITHUB_REPO_URL for reactjs app
                                                  # ⚠️  exports from 1st stack, STACK_REACTJS_URL
                                                  # ⚠️
                                                  # ⚠️  exports from 2nd stack, STACK_GITHUB_REPO_URL for flask app
                                                  # ⚠️  exports from 2nd stack, STACK_FLASK_URL
                                                  # ⚠️
                                                  # ⚠️  exports from 3rd stack, STACK_REDIS_URL
                                                  # ⚠️  exports from 4th stack, STACK_MYSQLDB_URL
                                                  # ⚠️  exports from 5th stack, STACK_ALGOLIA_URL

                                                  # stack-template.yaml once executed, produces artifacts to generates stack
                                                  # ⚠️  artifact from 1st stack, a github repository
                                                  # ⚠️  artifact from 1st stack, a gcp cloudrun app server - serving reactjs app

                                                  # ⚠️  artifact from 2nd stack, a github repository
                                                  # ⚠️  artifact from 2nd stack, a gcp cloudrun app server - serving flask app

                                                  # ⚠️  artifact from 3rd stack, a gcp redis instance
                                                  # ⚠️  artifact from 4th stack, a gcp mysqldb instance
                                                  # ⚠️  artifact from 5th stack, a algolia instance
