version: 1.0

name: ghstack-nextjs
description: ghstack for a nextjs app
branding:
 icon: 'githubpages.svg'
 color: 'blue'

inputs:
  - name: NODE_VERSION
    default: v12.22.4
    description: NODE_VERSION for nodejs stack
    validvalues:
    - v12.22.4
    - v14.17.4

  - name: NEXTJS_VERSION
    default: v11.0.1
    description: NEXTJS_VERSION for nextjs stack
    validvalues:
    - v11.0.1
    - v10.2.4
    - v10.2.3
    - v10.2.2
    - v10.2.1

  - name: enable-security-alerts
    default: true
    description: Enable Security Alerts

  - name: enable-vulnerability-alerts
    default: true
    description: Enable Vulnerability Alerts

configs:
  repo-metadata:
    topics:
    - nextjs
    - github-pages

  branches:
  - name: main
    parameters:
      enforce-admins: true
      dismiss-stale-reviews: true
      require-code-owner-reviews: true
      required-approving-review-count: 0
      allow-force-pushes: false
      allow-deletions: false

  environments: 
  - name: production
    parameters: 
    protected-branches: true
    custom-branch-policies: true
          
  security:
    parameters: 
      vulnerability-alerts: {{inputs.enable-vulnerability-alerts}}
      automated-security-fixes: {{inputs.enable-security-alerts}}

init:
- uses: ".github/workflows/stack-init.yaml"
