version: 1.0

name: ghstack-nextjs
description: ghstack for a nextjs app

inputs:
  - name: NPM_PASSWORD
    description: NPM_PASSWORD for dependabot workflow

  - name: SENDGRID_API_KEY
    description: SENDGRID_API_KEY for build notifications

  - name: reviewer-count
    default: 2
    description: Number of required reviewers for PR

  - name: enable-security-alerts
    default: true
    description: Enable Security Alerts

  - name: enable-vulnerability-alerts
    default: true
    description: Enable Vulnerability Alerts

configs:
  - topics:
    - nextjs
    - azure-cloud

  - branches:
    - name: master
      parameters:
        enforce-admins: true
        dismiss-stale-reviews: true
        require-code-owner-reviews: true
        required-approving-review-count: {{ inputs.reviewer-count }}
        allow-force-pushes: false
        allow-deletions: false

    - name: dev*
      parameters:
        enforce-admins: false
        dismiss-stale-reviews: true
        require-code-owner-reviews: false
        required-approving-review-count: 0
        allow-force-pushes: true
        allow-deletions: true

  - environments: 
    - name: production
      parameters: 
      protected-branches: true
      custom-branch-policies: true
      secrets:
        - name: NPM_PASSWORD
          value: {{inputs.NPM_PASSWORD}}
          
      - name: SENDGRID_API_KEY
        value: {{inputs.SENDGRID_API_KEY}}
          
  - security:
    parameters: 
      vulnerability-alerts: {{inputs.enable-vulnerability-alerts}}
      automated-security-fixes: true

github-apps:
- name: Azure
- name: codetree

init:
  uses: ".github/workflows/setup.yaml"
